# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Computer Applications in  Biology
description:      'Teaching the tools to get computers to do cool science'
url:              https://humberto-ortiz.github.io/semester-biology
baseurl:          /semester-biology
email:            humberto.ortiz@upr.edu
feedbackurl:      https://github.com/humberto-ortiz/semester-biology/issues/new
author:
  name:           'Humberto Ortiz-Zuazaga'
  url:            https://ccom.uprrp.edu/~humberto/

github:
  repo:           https://github.com/humberto-ortiz/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
